name: Benchmark

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Performance Regression Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}

      - name: Run performance regression tests
        run: |
          cargo test --release --test performance_test -- --nocapture --test-threads=1

      - name: Run benchmarks
        run: |
          cargo bench --bench sync_bench -- --output-format bencher | tee bench_output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tool: 'cargo'
          output-file-path: bench_output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

      - name: Compare benchmarks (PR only)
        if: github.event_name == 'pull_request'
        run: |
          # Checkout main branch for comparison
          git fetch origin main
          git checkout origin/main
          cargo bench --bench sync_bench -- --output-format bencher > main_bench.txt

          # Checkout PR branch
          git checkout -

          # Compare results
          echo "## Benchmark Comparison" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Comparing PR to main branch:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          diff main_bench.txt bench_output.txt || true >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

  perf-baseline:
    name: Record Performance Baseline
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run benchmarks and save baseline
        run: |
          cargo bench --bench sync_bench -- --save-baseline main

      - name: Store baseline
        uses: actions/upload-artifact@v4
        with:
          name: criterion-baseline
          path: target/criterion/
          retention-days: 90
